### ISSUE TITLE
Ebus configuration file

### ISSUE THREAD

**Issue by piacco** [koen-serneels/HomeAutomation#1]
Hello,
I have ebusd installed, but there are no configuration files for my roomthermostat (Vaillant Exacontrol E7C00) and my examaster (SBX00). In your blog i find out that you are using these products too. So my question could you help me decoding the code?

**Comment by koen-serneels** [comment]
Hi. All commands that I discovered (but this is for Bulex/AWB examaster) can be found in the source code at https://github.com/koen-serneels/HomeAutomation/tree/master/src/main/java/be/error/rpi/ebus/commands If your devices uses different ones, one way is to play with the thermostats (in case they are wired, at least) and sniff the bus, capture them, replay them and see if they do what you want. Another technique is to scan the internal registers after every change on the  thermostat and diff them to find out which ones are being modified as explained in my blog. Disclaimer: this is hacking up into the examaster, I'm not responsible if you brick your device ;-)

**Comment by piacco** [comment]
Thanks, did you accidentally sniff the code for the actual room temperature, i have tried but this one i can't find.

**Comment by koen-serneels** [comment]
No, as the actual room temperature is not measured by the heating system any more (as I've built a software thermostat) but by house automation components instead. This was the entire reason to set this up to begin with.
